# Generated by Django 5.0.6 on 2024-05-12 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
            ],
            options={
                'db_table_comment': 'detalles de la Entidad',
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table_comment': 'Especialista',
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table_comment': 'Clasificación de Prioridad',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table_comment': 'Clasificación de tipos de equipo',
            },
        ),
        migrations.CreateModel(
            name='TipoProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table_comment': 'Clasificación de tipos de problema',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.question')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('inventario', models.CharField(max_length=20)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.tipoequipo')),
            ],
            options={
                'db_table_comment': 'Detalles del equipo',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_responsable', models.CharField(max_length=100)),
                ('telefono_responsable', models.CharField(max_length=12)),
                ('fecha_entrada', models.DateField()),
                ('problema_reportado', models.TextField()),
                ('estado', models.CharField(choices=[('RECEPCIONADO', 'Recepcionado'), ('ASIGNADO', 'Asignado'), ('EVALUADO', 'Evaluado'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='RECEPCIONADO', max_length=20)),
                ('problema_real', models.TextField(blank=True, null=True)),
                ('solucionado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('verificado', models.BooleanField(default=False)),
                ('verificacion', models.TextField(blank=True, null=True)),
                ('fecha_verificacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.entidad')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.equipo')),
                ('especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.especialista')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.prioridad')),
                ('tipo_de_problema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.tipoproblema')),
            ],
        ),
    ]
