# Generated by Django 5.0.6 on 2024-05-07 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('inventario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('problema_reportado', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('problema_real', models.CharField(max_length=255)),
                ('tipo_de_problema', models.CharField(max_length=255)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.equipo')),
            ],
        ),
    ]
