# Generated by Django 5.0.6 on 2024-05-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_equipo_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='problema_real',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_de_problema',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
