# Generated by Django 5.0.6 on 2024-05-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_alter_registro_problema_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='problema_real',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_de_problema',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
